/**
 * Run this script once to create storage buckets in Supabase.
 *
 * Usage: npx tsx scripts/setup-storage.ts
 *
 * Buckets created:
 *   - contracts       (PRIVATE) — Contract PDFs uploaded during contract creation.
 *                                 Requires signed URLs (lib/storage/signedUrl.ts).
 *   - documents       (PRIVATE) — Document Vault: tenant ID scans, receipts,
 *                                 inspections, other PII. Requires signed URLs.
 *   - property-images (PUBLIC)  — Property photos (move-in / move-out). No PII.
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !serviceKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceKey);

async function upsertBucket(
  name: string,
  options: {
    public: boolean;
    fileSizeLimit: number;
    allowedMimeTypes: string[];
  }
) {
  const { data, error } = await supabase.storage.createBucket(name, options);
  if (error) {
    if (error.message.includes('already exists')) {
      // Update existing bucket to ensure correct public setting
      const { error: updateError } = await supabase.storage.updateBucket(name, {
        public: options.public,
        fileSizeLimit: options.fileSizeLimit,
        allowedMimeTypes: options.allowedMimeTypes,
      });
      if (updateError) {
        console.error(`✗ Failed to update bucket "${name}":`, updateError.message);
      } else {
        console.log(
          `✓ Bucket "${name}" already exists — settings updated (public=${options.public})`
        );
      }
    } else {
      console.error(`✗ Failed to create bucket "${name}":`, error.message);
      process.exit(1);
    }
  } else {
    console.log(`✓ Created bucket "${data.name}" (public=${options.public})`);
  }
}

async function main() {
  // PRIVATE bucket: contract PDFs (PDPA compliance)
  // Access must go through signed URLs generated by the service role.
  // See lib/storage/signedUrl.ts for the helper.
  await upsertBucket('contracts', {
    public: false,
    fileSizeLimit: 20 * 1024 * 1024, // 20MB
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  });

  // PRIVATE bucket: document vault (tenant ID scans, receipts, inspections)
  // Contains PII — access must go through signed URLs.
  await upsertBucket('documents', {
    public: false,
    fileSizeLimit: 25 * 1024 * 1024, // 25MB
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  });

  // PUBLIC bucket: non-sensitive property photos (move-in / move-out)
  await upsertBucket('property-images', {
    public: true,
    fileSizeLimit: 10 * 1024 * 1024, // 10MB
    allowedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
  });
}

main();
