-- H9: Make contracts AND documents storage buckets private (PDPA compliance)
--
-- Two PII-sensitive buckets exist:
--  - 'contracts'  → contract PDFs uploaded during contract creation
--  - 'documents'  → Document Vault (tenant_id scans, receipts, inspections)
--
-- A public bucket exposes these to anyone with a URL, bypassing RLS entirely.
-- Thai national ID card scans stored in category=tenant_id are PDPA-regulated.
--
-- Fix: update both buckets to public = false. Document reads must go through
-- signed URLs generated by the service role (see lib/storage/signedUrl.ts).
--
-- NOTE: property images use the separate 'property-images' bucket (public),
-- confirmed in app/api/properties/[id]/images/route.ts — no overlap, no impact
-- on property photo display.
--
-- Storage RLS policy: we rely entirely on signed URL generation via service
-- role rather than adding storage.objects RLS policies. Rationale: signed URLs
-- with short TTL (1 hour) are the correct mechanism for controlled document
-- access, and storage.objects path-string policies are brittle. Any route
-- returning a stored document URL should call getSignedDocumentUrl() from
-- lib/storage/signedUrl.ts instead of returning public_url directly.

UPDATE storage.buckets
SET public = false
WHERE id IN ('contracts', 'documents');

-- If the buckets haven't been created yet (fresh environment), this is a no-op.
-- The setup-storage.ts script has been updated to create them as private.
